site_name: Programação Orientada a Objeto
site_description: Lista de exercícios da disciplina de Programação em Microinformática do curso de Analise e Desenvolvimento de Sistemas da FATEC de Franca.
site_author: Getúlio Vinicius <getuliovinits@gmail.com>
google_analytics: ['UA-70830801-9', 'getuliovinicius.github.io/programacao.microinformatica/']
repo_url: https://github.com/getuliovinicius/programacao.microinformatica
repo_name: GitHub
edit_uri: blob/master/docs/mds/
remote_branch: gh-pages
remote_name: origin
docs_dir: 'mds'
pages:
  - Inicio: index.md
theme: readthedocs

